#define SIOCTL_TYPE 40000

#define IOCTL_SET_PID \
    CTL_CODE( SIOCTL_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS  )

#define IOCTL_SET_VA \
    CTL_CODE( SIOCTL_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS  )

#define IOCTL_SET_PFN \
    CTL_CODE( SIOCTL_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS  )

#define DRIVER_FUNC_INSTALL     0x01
#define DRIVER_FUNC_REMOVE      0x02

#define DRIVER_NAME       "SIoctl"